#spring:
#  mvc:
#    static-path-pattern: /res/**  #静态资源访问前缀
#  resources:
#    static-locations: [classpath:/xjStaticeFiles]
spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true   #开启页面表单的Rest功能（选择性开启）
    contentnegotiation:
      favor-parameter: true
server:
  servlet:
    context-path: /xj
